getoutreach/extensibility-sdk

docs/schema/2.0/manifest.schema.json
tests/validator.test.ts

For some reason, we had been using "manifest.app" instead of "manifest.store" in the JSON schema. Renamed.

Rename section manifest.app -> manifest.store in the JSON schema.

---

docs/url-parsing.md
package.json
src/legacy/ManifestTranslator.ts
src/legacy/ManifestV1.ts
src/manifest/Application.ts
src/manifest/extensions/Extension.ts
tests/translator.test.ts
tests/validator.test.ts

[OREX-741]
In order to avoid having non-intuitive, negative manifest property names we are renaming **notUseSdk** to **dsiableTimeoutMonitoring**
[OREX-741]: https://outreach-io.atlassian.net/browse/OREX-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OREX-741 Renaming notUseSdk to disableTimeoutMonitoring

---

docs/manifest.md
docs/schema/2.0/manifest.schema.json
src/legacy/ManifestTranslator.ts
src/manifest/Application.ts
src/manifest/ManifestWebhook.ts
src/manifest/api/WebHookEvents.ts
src/sdk/Validator.ts
tests/validator.test.ts

This PR is defining webhooks-related application attributes in manifest,  SDK, and in OREX service schema 
`app {
webhooks: {
events: ["*"],
url: "https://application-host.com/webhook"
}
}`

[oree-842] Adding support for webhook to manifest

---

package.json
src/index.ts
src/manifest/extensions/ExtensionGuards.ts
src/manifest/extensions/ExtensionType.ts
src/manifest/extensions/editor/ContentExtensionType.ts
src/manifest/extensions/editor/EditorExtension.ts
src/manifest/extensions/shell/ShellExtensionType.ts

Per review comment, creating dedicated enum for editor extension type so it will change from "shell-editor" to "content-editor"

Creating dedicated extension type enum for editor

---

package.json
src/context/host/AccountContext.ts
src/context/host/AccountContextUtils.ts
src/context/host/OpportunityContext.ts
src/context/host/OpportunityContextUtils.ts
src/context/host/ProspectContext.ts
src/context/host/ProspectContextUtils.ts
tests/AccountContextUtils.test.ts
tests/OpportunityContextUtils.test.ts
tests/ProspectContextUtils.test.ts

Restoring back removed deprecated property for external provider information as it is needed for backward compatibility

[oree-883] Restoring depricated external property on account, prospect and opportunity

---

package.json
src/legacy/ManifestTranslator.ts

With the new extension, this is now failing. Adding the new extension type to the switch.

Fix extension hydratation for Editor ext

---

package.json
src/context/keys/ClientContextKeys.ts

To pass these query parameters to the iframe in TextEditor, their keys have to be defined and allowed.

[OREE-852] Add context keys needed for content editor

---

package.json
src/manifest/extensions/editor/EditorExtension.ts

[OREE-861]
Editor content extension can receive additional account/prospect/opportunity properties in some scenarios. 
[OREE-861]: https://outreach-io.atlassian.net/browse/OREE-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OREE-861] Expanding editor extension context

---

docs/schema/2.0/manifest.schema.json

we were not enforcing schema at all in orexservice
with these fixes it can be used to really validate uploaded schema server-side (with a few exceptions)
changes
- identifer is in root, not store
- categories enum must be inside items
- unique values enforced in array where possible
- required fields updated a bit but this conditions is ignored in orexservice as manifests are being saved half-empty and validated before publishing
- apiS2S updated to proper schema format
- additional properties are not allowed (unless it's localized text)

fix: manifest schema made actually usable in orexservice

---

docs/schema/2.0/manifest.schema.json

- identifier should not start/end with `-`
- version can be single number
- there is no extension version
- extension identifier must not contain `:` (same rules as for app identifier)

update manifest's identifier format and version

---

docs/configuration.md
docs/manifest.md
docs/schema/2.0/manifest.schema.json
package.json

Make it URI template to allow parameters substitution as described here https://github.com/getoutreach/extensibility-sdk/blob/main/docs/manifest.md#url-host.

fix: schema: Update host url type

---

package.json
src/index.ts

We were sending warning message to the client if the loading time of an addon took more than 2 seconds. Proposed solution was to remove the showing in client and only log it.
After a bit of investigation how does all of this work on client, I found out that we are not blocking any message to come through. I don't feel like cherrypicking one message and blocking it on client is the best solution. It's probably worth to open a discussion on the notifications from SDK in the team once the whole team is together.
Also one there is a one thing where [in client](https://github.com/getoutreach/client/blob/dbf77263eb699d4b15d15a4d0defe7ad172506f6/packages/composites/client-extensibility/src/components/shared/ExtensionArea.tsx#L180) there is a `isTranslatedString` check where it shouldn't show any …

[OREE-1681] fix: Only log the load warning message

---

.circleci/config.yml
.npmrc
package.json

[OREE-2005]
[NPMJS.org](http://npmjs.org/) is deprecated for security reasons at Outreach and we need to move our public extensibility SDK package to Github Packages. See [DT-4053](https://outreach-io.atlassian.net/browse/DT-4053) for more info
A part of that is renaming from `@outreach/extensibility-sdk` to `@getoutreach/extensibility-sdk`
[OREE-2005]: https://outreach-io.atlassian.net/browse/OREE-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-4053]: https://outreach-io.atlassian.net/browse/DT-4053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OREE-2005] Publish Extensibility SDK into Gihub Packages

---

.circleci/config.yml
.npmrc
package.json

Reverts getoutreach/extensibility-sdk#95
We won't switch the public package to GH Packages after all. See [OREE-2005]
[OREE-2005]: https://outreach-io.atlassian.net/browse/OREE-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "[OREE-2005] Publish Extensibility SDK into Gihub Packages"

---

src/context/interfaces/IOutreachContext.ts
tests/index.test.ts

Added test for presence of OutreachContext.email
A follow up of #104 
[OREE-2123]: https://outreach-io.atlassian.net/browse/OREE-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OREE-2123] Added test for presence of OutreachContext.email

---

package.json
src/index.ts
src/legacy/ManifestTranslator.ts
tests/translator.test.ts

Applicaiton configuraton is inaccessible in outreach context. This fixes the issue
This line is removed because it messed with the expected output of the outreach context. It expected ConfigurationValue, but got ConfigurationItem instead
```javascript
if (app.configuration) {
application.configuration = app.configuration.map((item) => Object.assign(new ConfigurationItem(), item));
}
```
[OREE-2061]: https://outreach-io.atlassian.net/browse/OREE-2061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OREE-2061] show configuration in outreach context

---

.circleci/config.yml

[DT-4171]: https://outreach-io.atlassian.net/browse/DT-4171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-4171] Update CI credentials for npm publish to work

---

package.json
src/index.ts

This load handler does nothing useful except confusing users displaying a toastr error message. It serves no purpose at all, that's why we are removing this
[ADE-2062]: https://outreach-io.atlassian.net/browse/ADE-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
After this is merged, I'll need to bump `client` repo sdk version

[ADE-2062] fix: remove default implementation of load handler

---

docs/schema/2.0/manifest.schema.json
package.json
src/manifest/store/Category.ts

A follow up to `orexservice` PR https://github.com/getoutreach/orexservice/pull/745 that adds a new category for new layout sections tile
[ADE-2678]: https://outreach-io.atlassian.net/browse/ADE-2678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ADE-2678] feat: add "grouping_and_navigation" category

---

docs/schema/2.0/manifest.schema.json

Made manifest-url optional. It's for a nicer UX, but it isn't necessary.
[ADS-1478]
[ADS-1478]: https://outreach-io.atlassian.net/browse/ADS-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: manifest-url is optional

---

.github/CODEOWNERS
docs/schema/2.0/opdpManifest.schema.json

An iteration of the auth in OPDP that allows token in header.
We will support 2 modes - api token in a header and oauth. We decided not to provide any more fields in the manifest for oauth for now. It won't be specified in the manifest. We can always formalize it later on.
[ADS-1542]
[ADS-1542]: https://outreach-io.atlassian.net/browse/ADS-1542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: updated auth for OPDP

---

docs/schema/2.0/manifest.schema.json
package.json
src/manifest/store/Category.ts

There are no mentioned of this category in the `client` repo, and also there are no tiles under this category in orexservice:
https://github.com/search?q=repo%3Agetoutreach%2Forexservice+conversation_intelligence&type=code

feat: remove unused category
