getoutreach/extensibility-sdk

docs/sdk.md, package.json, src/index.ts, src/manifest/extensions/tabs/TabExtension.ts, src/manifest/extensions/tabs/types/AccountTabExtension.ts, src/sdk/logging/DefaultLogger.ts, src/sdk/logging/ILogger.ts, src/sdk/logging/Logger.ts, src/sdk/services/tokenService.ts, src/utils.ts, tests/validator.test.ts
Export extension types for usage in client code
=> Export extension types

package.json, src/index.ts, src/manifest/extensions/Extension.ts, src/manifest/extensions/ExtensionType.ts, src/manifest/extensions/tabs/types/AccountTabExtension.ts, src/manifest/extensions/tabs/types/ApplicationTabExtension.ts, src/manifest/extensions/tabs/types/OpportunityTabExtension.ts, src/manifest/extensions/tabs/types/ProspectTabExtension.ts
Exposed type property on Extension base class
Made successors' types more precise
=> Extension type changes

docs/manifest.md, docs/schema/2.0/manifest.schema.json
Added regex to validate the Application Identifier. Verified here https://www.jsonschemavalidator.net/
=> fix: add pattern for the manifest schema v2.0 [OREX-578]

docs/manifest.md, docs/schema/2.0/manifest.schema.json, src/manifest/ManifestAuthor.ts, src/manifest/ManifestStore.ts
Align Manifest keys and terms used across documentation, schema and code
=> Documentation update

docs/configuration.md, docs/manifest.md, docs/schema/2.0/manifest.schema.json, src/legacy/ManifestTranslator.ts, src/manifest/ManifestStore.ts, src/manifest/store/Media.ts, src/sdk/Validator.ts, tests/translator.test.ts, tests/validator.test.ts
Contains all the changes in https://github.com/getoutreach/extensibility-sdk/pull/15 plus URI -> URL change.
See [What’s the Difference Between a URI and a URL?](https://danielmiessler.com/study/difference-between-uri-url/#:~:text=The%20terms%20%E2%80%9CURI%E2%80%9D%20and%20%E2%80%9C,as%20HTTPs%20%2C%20FTP%20%2C%20etc.) for justification
=> Documentation update (with urls)

package.json, src/context/OutreachContext.ts, src/context/host/OrganizationContext.ts, src/context/keys/AllContextKeys.ts, src/context/keys/OrganizationContextKeys.ts, src/index.ts, src/legacy/ManifestTranslator.ts, src/manifest/extensions/shell/ShellExtension.ts, src/manifest/extensions/tabs/types/AccountTabExtension.ts, src/manifest/extensions/tabs/types/OpportunityTabExtension.ts, src/manifest/extensions/tabs/types/ProspectActionTabExtension.ts, src/manifest/extensions/tabs/types/ProspectTabExtension.ts, src/manifest/extensions/tabs/types/ReportsTabExtension.ts, src/manifest/extensions/tiles/TileSize.ts, src/manifest/extensions/tiles/types/AccountTileExtension.ts, src/manifest/extensions/tiles/types/HomeTileExtension.ts, src/manifest/extensions/tiles/types/OpportunityTileExtension.ts, src/manifest/extensions/tiles/types/ProspectTileExtension.ts, yarn.lock
Adding support for organization context properties
=> #oree-35 Org context props

docs/context.md, package.json, src/context/host/AccountContext.ts, src/context/host/AccountContextUtils.ts, src/context/host/CustomContext.ts, src/context/host/ExternalInfoContext.ts, src/context/host/ExternalInfoProvider.ts, src/context/host/ExternalInfoUtils.ts, src/context/host/OpportunityContext.ts, src/context/host/OpportunityContextUtils.ts, src/context/host/ProspectContext.ts, src/context/host/ProspectContextUtils.ts, src/context/keys/AccountContextKeys.ts, src/context/keys/ClientContextKeys.ts, src/context/keys/OpportunityContextKeys.ts, src/context/keys/ProspectContextKeys.ts
[oree-266]
Changes:
- Moving from plugin[] to plugin (old implementation kept to keep the backward compatibility but marked as depricated)
- Adding domain property to account and prospect
- Adding address properties to prospect
=> oree-266 Updating SDK to reflect better ORCA model

package.json, src/index.ts
[OREE-597]
Need to export tile setting type to be used in client.
[OREE-597]: https://outreach-io.atlassian.net/browse/OREE-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OREE-597] Export tile settings

package.json, src/manifest/extensions/Extension.ts, src/manifest/extensions/tabs/TabExtension.ts, src/manifest/extensions/tiles/TileExtension.ts
Small refactoring to simplify client implementation
=> Defining context with full scope on extension level

package.json, src/index.ts, src/manifest/extensions/ExtensionGuards.ts, src/manifest/extensions/shell/types/KnowledgeShellExtension.ts, src/utils.ts, tests/ExtensionGuards.test.ts
Adding a few tile extension type guard functions
=> Extension type guards

package.json, src/index.ts, src/sdk/RuntimeContext.ts, src/sdk/messages/InitMessage.ts, src/sdk/messages/Message.ts, src/sdk/services/oauthService.ts, tests/oauthService.test.ts
More auth flow related fixes + linting the markup files
=> [oree-834] auth flow fixes + docs linting

package.json, src/index.ts, src/sdk/messages/MessageType.ts, src/sdk/messages/OAuthDialogCompletedMessage.ts, tests/index.test.ts
SDK part of the fix for a bug of authorization promise not being resolved after the OAuth compeltes
=> [oree-834] Resolving sdk.authorize() promise

package.json, src/index.ts, src/legacy/ManifestTranslator.ts, src/manifest/Application.ts, src/manifest/ManifestApi.ts, src/manifest/ManifestConfiguration.ts, src/manifest/extensions/editor/EditorExtension.ts, tests/configuration.test.ts, tests/editorExtension.test.ts, tests/translator.test.ts
Updating manifest to support upcoming dev portal work:
- editor extensions regions are removed (extension will work in all of the regions)
- config is extended now to have items and externalUrl
- API section has an array of public keys
=> [oree-847][oree-860] - Manifest updates

package.json, src/index.ts, src/utils.ts
Creating type guard function which I will need in client to extract appId out of the routing props
=> oree-870 Adding type guard needed for client  fix

docs-dev-portal/sdk.md
will be reverted when the feature is released
=> Hide enhanceTextEditor docs for now

package.json, src/index.ts, src/manifest/extensions/editor/EditorExtension.ts, src/manifest/extensions/editor/EditorSettings.ts, tests/editorExtension.test.ts
There are 0...n recommended sizes (and not 0..1) - this PR correcting that
=> [OREE-1029] Correcting recommended size settings

package.json, src/context/keys/ProspectContextKeys.ts
#OREE-1088
Adding to prospect context keys keys for prospect name, first name and last name
=> [OREE-1088] Missing prospect context keys

package.json, src/context/host/EmailContext.ts, src/context/interfaces/IEmailContext.ts, src/context/keys/AllContextKeys.ts, src/context/keys/EmailContextKeys.ts, src/index.ts, src/manifest/extensions/editor/EditorExtension.ts, tests/editorExtension.test.ts
Adding to SDK support for upcoming email context parameters
=> [oree-1100] Email context support

package.json, src/manifest/api/Scopes.ts
[OREE-1115]
Limit list of available scopes
[OREE-1115]: https://outreach-io.atlassian.net/browse/OREE-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Remove non-public OAuth scopes

package.json, src/context/host/OrganizationContext.ts, src/context/host/UserContext.ts, src/context/interfaces/IOrganizationContext.ts, src/context/interfaces/IUserContext.ts, src/context/keys/OrganizationContextKeys.ts, src/context/keys/UserContextKeys.ts
Based on the customer requirements user needs to have two IDs:
1. user.id -> unique cross-org user identity (guid)
2. user.orgUserId -> identity inside of a ures org (int starting in every org from 1,2...
=> [OREE-1134] User is having two IDs (org one and cross org one)

package.json, src/index.ts, src/sdk/messages/MessageGuards.ts, tests/messageGuards.test.ts
Support for close Galaxy close message
=> [OREE-1154] Galaxy close message support

docs/scopes.md, src/manifest/api/Scopes.ts
[ORES-1792](https://outreach-io.atlassian.net/browse/ORES-1792)
[ORES-1792]: https://outreach-io.atlassian.net/browse/ORES-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ORES-1792] messenger scopes removed

package.json, src/context/host/OpportunityContext.ts, src/context/host/OpportunityContextUtils.ts, src/context/interfaces/IOpportunityContext.ts, src/context/keys/OpportunityContextKeys.ts, tests/OpportunityContextUtils.test.ts
[OREE-1346]
Adding support for additional opportunity properties:
- account domain
- account external id
- account external provider
- account id
- account name
- owner email
- owner id
- owner name
- owner username
[OREE-1346]: https://outreach-io.atlassian.net/browse/OREE-1346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OREE-1346] Additional opportunity params

docs/schema/2.0/manifest.schema.json
[OREE-1167]
Added template field to manifest and schema.
[OREE-1167]: https://outreach-io.atlassian.net/browse/OREE-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add template field to extensions

package.json, src/context/host/OpportunityContext.ts, src/context/host/OpportunityContextUtils.ts, src/context/interfaces/IOpportunityContext.ts, src/context/keys/OpportunityContextKeys.ts, tests/OpportunityContextUtils.test.ts
Add support for additional opportunity parameter - account custom id
=> Add support for opportunity.accountCustomId

package.json, src/context/host/ExternalInfoProvider.ts, tests/AccountContextUtils.test.ts, tests/OpportunityContextUtils.test.ts, tests/ProspectContextUtils.test.ts
just changed 2 -> 3 and look at a size of it :-D
=> Fixed value for Dynamics in externalInfo

package.json, src/context/host/OpportunityContext.ts, src/context/host/OpportunityContextUtils.ts, src/context/interfaces/IOpportunityContext.ts, src/context/keys/OpportunityContextKeys.ts, tests/OpportunityContextUtils.test.ts
[OREE-1874](https://outreach-io.atlassian.net/browse/OREE-1874)
-------
Add support for additional opportunity parameter - stage
[OREE-1784]: https://outreach-io.atlassian.net/browse/OREE-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OREE-1874]: https://outreach-io.atlassian.net/browse/OREE-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OREE-1874] add stage to opportunity contextual params

.circleci/config.yml
=> [OREE-1878] Extensibility SDK is not publishing NPM package

docs/schema/2.0/manifest.schema.json
[ORES-2300]
[ORES-2300]: https://outreach-io.atlassian.net/browse/ORES-2300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: new category for account plan

examples/my-first-outreach-app/helpers.js, examples/my-first-outreach-app/index.js, package.json, src/context/OutreachContext.ts, src/index.ts
Fix missing `EmailContext` in `OutreachContext`
[OREE-2123]: https://outreach-io.atlassian.net/browse/OREE-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OREE-2123] Fix missing EmailContext in OutreachContext

examples-be/README.md, examples-be/src/main.ts
Updated S2S example project with proper URLs and env. vars in README
[OREE-2157]: https://outreach-io.atlassian.net/browse/OREE-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OREE-2157] Updated S2S example project

package.json, src/manifest/store/Category.ts
Adding account plan category to enum.
=> [OREE-2169] feat: adding Account plan category

.circleci/config.yml, .github/CODEOWNERS, .github/pull_request_template.md, .npmrc, dts-bundle.json, examples/iframe-app/package.json, examples/iframe-app/yarn.lock, examples/my-first-outreach-app/package.json, examples/my-first-outreach-app/yarn.lock, package.json, tests/tileExtension.test.ts
Migrate off of NPM registry to github package registry.
https://outreach-io.atlassian.net/browse/DT-4171
=> chore: migrate to use github packages

package.json
I forgot to bump up the version so publish didn't happen in #111
=> [DT-4171] Bump up version to publish 🙈

package.json, src/manifest/api/ScopesS2S.ts
[ORES-2341]
[ORES-2382]: https://outreach-io.atlassian.net/browse/ORES-2382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ORES-2341]: https://outreach-io.atlassian.net/browse/ORES-2341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ORES-2341] S2S scopes updated

src/manifest/extensions/tiles/TileExtensionType.ts
Adding new tile extension type for strike zone reporting page. 
[RA-3527](https://outreach-io.atlassian.net/browse/RA-3527)
[RA-3527]: https://outreach-io.atlassian.net/browse/RA-3527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RA-3527 Add Strike Zone Tile Extension Type

package.json
=> RA-3527 Update version for Strike Zone Tile Extension Type

.github/CODEOWNERS
Changed code owners to ADE team
[ADE-554]
[ADE-554]: https://outreach-io.atlassian.net/browse/ADE-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: changed code owners

docs/schema/2.0/manifest.schema.json, package.json
Add a new "Meetings" category for extensibility applications
[ADS-570]
[ADS-570]: https://outreach-io.atlassian.net/browse/ADS-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ADS-570: add new meetings category

src/manifest/api/Scopes.ts
We would like to surface OAuth scopes for custom objects
[ADS-815]
[ADS-815]: https://outreach-io.atlassian.net/browse/ADS-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Regenerate Scopes

package.json, scripts/README.md, src/manifest/api/Scopes.ts
It is needed by ORCS, they added those scopes to API-Proxy, extensibility-sdk needs to be updated
+ added readme for anyone else that would like to run the scopesgen
[XX-XX]
=> fix: Generate Some Missing Scopes For ORCS

package.json, src/manifest/api/Scopes.ts
This PR adds missing scopes for CurrencyTypes Object 
IND:OM Team.
[OPM-174](https://outreach-io.atlassian.net/browse/OPM-174)
[OPM-174]: https://outreach-io.atlassian.net/browse/OPM-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(currencyType): Adding missing scopes IND:OM Team

package.json, src/manifest/api/Scopes.ts
=> feat: Make Read Batches Public

package.json, src/manifest/api/Scopes.ts
[ADS-903]
[ADS-903]: https://outreach-io.atlassian.net/browse/ADS-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: BulkActions Require batch.write

package.json, src/manifest/api/Scopes.ts
The batches scopes were made public and bulk actions are now executable with Oauth token. Same can be done for imports.
[ADS-903]
[ADS-903]: https://outreach-io.atlassian.net/browse/ADS-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Make Import Scopes Public

package.json, src/manifest/extensions/tiles/TileExtensionType.ts, src/manifest/store/Category.ts
[RA-4177](https://outreach-io.atlassian.net/browse/RA-4177)
Adding new Tile Extension Type for Custom Dashboard 
[RA-4177]: https://outreach-io.atlassian.net/browse/RA-4177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RA-4177 Add Custom Dashboard Tile Extension Type

package.json, src/manifest/api/ScopesS2S.ts
Updating after apiproxy change: https://github.com/getoutreach/apiproxy/pull/660
[XX-XX]
=> fix: Imports + Batches S2S scope

docs/schema/2.0/manifest.schema.json, package.json
[RA-4263](https://outreach-io.atlassian.net/browse/RA-4263)
[RA-4263]: https://outreach-io.atlassian.net/browse/RA-4263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RA-4263 Add Reports category to manifest

package.json, src/manifest/api/Scopes.ts
[ADS-969]
[ADS-969]: https://outreach-io.atlassian.net/browse/ADS-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: scope list updated

package.json, src/manifest/api/Scopes.ts, src/manifest/api/ScopesS2S.ts
[ADS-1173]
[ADS-1173]: https://outreach-io.atlassian.net/browse/ADS-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: batchItem scope added [ADS-1173]

package.json, src/manifest/store/Category.ts
[ADE-2404]
[ADE-2404]: https://outreach-io.atlassian.net/browse/ADE-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ADE-2404] - Added Records category

package.json, src/configuration/ConfigurationItemType.ts
Added password type to `ConfigurationItemType`
[ADS-1477]: https://outreach-io.atlassian.net/browse/ADS-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ConfigurationItemType): Added password type [ADS-1477]

docs/schema/2.0/manifest.schema.json, docs/schema/2.0/opdpManifest.schema.json
Added support for password type input. 
[ADS-1477]
[ADS-1477]: https://outreach-io.atlassian.net/browse/ADS-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added password type input

.github/pull_request_template.md, docs/schema/2.0/opdpManifest.schema.json
Adds support for specifying which fields are covered by the enrich endpoint.
[ADS-1510]
[ADS-1510]: https://outreach-io.atlassian.net/browse/ADS-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: opdp manifest enrich fields

docs/schema/2.0/opdpManifest.schema.json
Updates the OPDP manifest to the current version.
[ADS-1550]
[ADS-1550]: https://outreach-io.atlassian.net/browse/ADS-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: OPDP manifest update

.github/CODEOWNERS, docs/schema/2.0/opdpManifest.schema.json, package.json, tests/opdpManifest.test.ts, yarn.lock
Updates to the latest opdp manifest file.
Also introduces simple tests that verify that we're not leaking the internal properties of opdp manifest to external users.
[ADS-1625]
[ADS-1625]: https://outreach-io.atlassian.net/browse/ADS-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: updated opdp manifest

package.json, src/manifest/api/Scopes.ts, src/manifest/api/ScopesS2S.ts
[ADS-1663]
[ADS-1663]: https://outreach-io.atlassian.net/browse/ADS-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: batchItems.write scope added [ADS-1663]

docs/schema/2.0/manifest.schema.json, package.json, src/manifest/store/Category.ts
[ORCS-4724]
Adding "agents" category. This would serve as bucket for current and further upcoming agent tiles
This category would be utilized now for research agent tiles
[ORCS-4724]: https://outreach-io.atlassian.net/browse/ORCS-4724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Adding "agents" category

docs/schema/2.0/manifest.schema.json, package.json, src/manifest/store/Category.ts
Added Execution And Performance Category
[ORCA-5206]
[ORCA-5206]: https://outreach-io.atlassian.net/browse/ORCA-5206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCA-5206: Added Execution And Performance Category
